### ISSUE TITLE
Crash when entering world blender dimension.

### ISSUE THREAD

**Issue by irunatbullets** [TelepathicGrunt/WorldBlender-Fabric#11] opened 2021-05-30 08:25 UTC
Just logging this here incase it gets missed in AOF discord.

Trying to help with reproducing the 'everything is just oceans' issue on my home server, but ended up with a different crash.

Modpack is AOF 2.8
world_blender-1.16.5-2.1.5.jar

Game crashes when I enter world blender dimension https://paste.alloffabric.com/todavojuxa.yaml I can see one or two chunks in the map but it's all just void on the client.

**Comment by TelepathicGrunt** [comment] 2021-05-31 01:09
```
java.lang.Error: Watchdog
at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.waitForTasks(ThreadExecutor.java:139)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:129)
	at net.minecraft.server.world.ServerChunkManager.getChunkBlocking(ServerChunkManager.java:1269)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager.java:1165)
	at net.minecraft.world.World.getChunk(World.java:209)
	at com.telepathicgrunt.worldblender.dimension.AltarManager.isWorldOriginTicking(AltarManager.java:50)
	at com.telepathicgrunt.worldblender.dimension.AltarManager.tick(AltarManager.java:34)
	at net.minecraft.server.world.ServerWorld.handler$cle000$tickAltar(ServerWorld.java:12101)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:871)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:312)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)

"Worker-Main-29" Id=437 RUNNABLE
at net.minecraft.util.math.noise.PerlinNoiseSampler.sample(PerlinNoiseSampler.java:576)
	at net.minecraft.util.math.noise.OctavePerlinNoiseSampler.sample(OctavePerlinNoiseSampler.java:131)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.getRandomDensityAt(NoiseChunkGenerator.java:355)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.sampleNoiseColumn(NoiseChunkGenerator.java:302)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.sampleNoiseColumn(NoiseChunkGenerator.java:202)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.sampleHeightmap(NoiseChunkGenerator.java:401)
	at net.minecraft.world.gen.chunk.NoiseChunkGenerator.getHeight(NoiseChunkGenerator.java:378)
	at net.minecraft.world.gen.chunk.ChunkGenerator.getHeightOnGround(ChunkGenerator.java:326)
	
```

So it seems while the world is ticking, I go to have some chunks around world origin to be generated so I can place the altar after worldgen. However, something about these chunks is either taking longer or deadlocking. Here, it seems something was sampling the heightmap like crazy and caused the server to time out.

I need the full thread dump as the mini thread dump here cut off "Worker-Main-29" Id=437 RUNNABLE before it could say exactly which mod was sampling heightmap a lot and caused the server to time out. (also, make sure your watchdog timer isn't too short as well. Anything more than 30seconds should be fine i think)

**Comment by irunatbullets** [comment] 2021-05-31 09:55
Is there a flag or setting I need to enable to get the full thread dump? All I get from google is other people's crash reports :\

**Comment by TelepathicGrunt** [comment] 2021-05-31 12:50
I think the current truncated thread dump is actually done by another mod trying to be helpful. maybe the threaded dimension mod. An idea is try making the server watchdog timer be 5 minutes, go to the same spot on server, wait for it to hand, and then use VisualVm to get a threadump. I can try and do it later today myself. May I have the AOF version you are using? (and see if that is ok but I may be able to reproduce it without seed)

**Comment by irunatbullets** [comment] 2021-05-31 13:56
The version of AOF is the one pinned to aof-dev channel by AK9 All_of_Fabric_3-2.8.0.zip. The only difference being adding World Blender to the pack. For the server I just ran a 2.7.4 server, then removed then replaced all of the mods/config/kubjs/etc with stuff from 2.8.0

I've tried to capture a thread dump using visualvm - but I'm not sure if it's helpful. It seems sometimes I have to move a little bit for this crash to happen https://paste.alloffabric.com/pevuratiki.properties
, or perhaps it's just a timing thing.

Setting watchdog to 5 minutes prevents the game from crashing (and the end dragon spawns) by the looks of it, however it's pretty unplayable as a lot of the area is still void.

All of this is reminding me of the issue I had with the EU server last week where the end dragon dying was causing the server to crash - there was also mention of this "sampling the heightmap like crazy".

**Comment by TelepathicGrunt** [comment] 2021-05-31 14:50
last time, it was due to me forcing 16x16 chunks to generate at once due to vanilla code iirc or something like that. The current code only forces 4 chunks to generate. if 4 chunks cant, then there's an issue somewhere with something trying to generate. The "a lot of the area is void" is the server deadlocking or stalling as it is stuck generating one of the 4 chunks and that's when I would need to do a proper thread dump with visualvm and get the full stacktrace of every thread.

**Comment by TelepathicGrunt** [comment] 2021-06-01 00:04
In AOF discord, I got the problematic AOF3, booted up my own server, and joined it. I went to world origin twice in single player and once on server. No hand or deadlock or crash occurred. Seems to be an issue with the server instance itself that AOF3 is using. hopefully you all can figure it out as I can't reproduce this
![image](https://user-images.githubusercontent.com/40846040/120250196-3b68ed00-c24b-11eb-900f-d49d5f34c7a7.png)

**Comment by irunatbullets** [comment] 2021-06-02 14:04
I've just reproduce this using the released 2.8.1 server https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files

I am using `/execute in world_blender:world_blender run tp irunatbullets ~ ~ ~` to teleport myself to WB.

My server only has 4GB of ram allocated to it - so perhaps this is the problem.

However, it doesn't crash in Single player but is extremely slow to load, with a lot of void for a while.

![2021-06-02_16 02 03](https://user-images.githubusercontent.com/344908/120494417-18117f80-c3bc-11eb-84cf-99761a08f3da.png)

**Comment by irunatbullets** [comment] 2021-06-02 14:12
Here's the latest crash report from the release 2.8.1 server. https://paste.alloffabric.com/noxodikuge.yaml

**Comment by TelepathicGrunt** [comment] 2021-06-02 17:37
You dont have the right config. Ask monster for the real config that AOF3 will use which will blacklist most of the junk from being imported. With hundreds or even a thousand feature imported and all trying to generate in the chunks is causing your server to time out. That's why I can't reproduce it with the correct config where monster filtered out a majority of the stuff from the dimension.

**Comment by TelepathicGrunt** [comment] 2021-06-02 19:19
Closing the issue report as it is actually due to world blender working as intended and trying to spawn everything unfiltered due to config defaults. For anyone else reading this with their own servers that has a massive ton of mods on, try blacklisting all the most resource intensive features. Then try also increasing the timeout threshold for the server watchdog to be much higher so world blender has more time to generate the few chunks it needs to make. But yeah, there's a lot of worldgen stuff from other mods that is quite performance eating and should be blacklisted.

**Closed as completed by TelepathicGrunt** 2021-06-02 19:19 UTC
Labels: Not a bug
